### ISSUE TITLE
Can't run example project

### ISSUE THREAD

**Issue by mirroringcontact** [wsvn53/adb-mobile#1]
Please try run project with xcode 14 on simulator and iPhone. 

Simulator error:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/91149176/200457094-a0716242-9bea-477c-b778-77832e8cfa17.png">

iPhone error: 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/91149176/200457647-7fc28b15-bb80-43b8-bf85-d41c7b8fdc4a.png">

**Comment by cagnulein** [comment]
same issue with Xcode 13

**Comment by wsvn53** [comment]
This is caused by mismatched protobuf version, please update the latest code of adb-mobile and execute:

```
brew unlink protobuf && brew install porting/protobuf.rb
```

This command will install correct version of protobuf, after that, you can execute `make` again to re-compile libadb.

**Comment by cagnulein** [comment]
wow thanks, i'm trying!

**Comment by cagnulein** [comment]
i'm getting no available formula for "porting/protobuf.rb"
Am I doing something wrong?

**Comment by wsvn53** [comment]
> i'm getting no available formula for "porting/protobuf.rb" Am I doing something wrong?

Have you run `git pull` to update adb-mobile code?

You can also download this file https://github.com/wsvn53/adb-mobile/blob/main/porting/protobuf.rb, and brew install it.

**Comment by cagnulein** [comment]
> Have you run `git pull` to update adb-mobile code?

yes just pull it today



> You can also download this file https://github.com/wsvn53/adb-mobile/blob/main/porting/protobuf.rb, and brew install it.

ok, thanks i try

**Comment by wsvn53** [comment]
> i'm getting no available formula for "porting/protobuf.rb" Am I doing something wrong?

And make sure you are executing at root of adb-mobile source path.

**Comment by cagnulein** [comment]
done but i'm getting the same error.

![image](https://user-images.githubusercontent.com/48216/205959951-53b154e3-031f-464a-8cb2-47202864831e.png)

**Comment by mirroringcontact** [comment]
Thank you. I run it!

**Comment by cagnulein** [comment]
> Thank you. I run it!

so it worked for you?

**Comment by mirroringcontact** [comment]
Yes. Connect to device and commands works fine. Thank you!

**Comment by wsvn53** [comment]
> done but i'm getting the same error.
> 
> ![image](https://user-images.githubusercontent.com/48216/205959951-53b154e3-031f-464a-8cb2-47202864831e.png)

You can check the product archs by execute `file output/lbadb.a`, does that file contains x86_64?

**Comment by cagnulein** [comment]
@mirroringcontact great! So there is hope also for me :)
@wsvn53 I will check again this in 2 days, I'm travelling right now! Thanks for your help so far and for this amazing project!

**Comment by cagnulein** [comment]
@wsvn53 yes it is
```
otool -hv libadb.a 
Archive : libadb.a
libadb.a(constants.o):
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00      OBJECT     4        992 SUBSECTIONS_VIA_SYMBOLS
```

maybe it's because I used the cmake from brew instead of the one in your repository?

**Comment by wsvn53** [comment]
> @wsvn53 yes it is
> ```
> otool -hv libadb.a 
> Archive : libadb.a
> libadb.a(constants.o):
> Mach header
>       magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
> MH_MAGIC_64   X86_64        ALL  0x00      OBJECT     4        992 SUBSECTIONS_VIA_SYMBOLS
> ```
> 
> maybe it's because I used the cmake from brew instead of the one in your repository?

Please provide your compiling logs if possible.

**Comment by cagnulein** [comment]
sure @wsvn53 
[Build target adb-demo_2022-12-07T14-10-38.txt](https://github.com/wsvn53/adb-mobile/files/10176309/Build.target.adb-demo_2022-12-07T14-10-38.txt)

**Comment by wsvn53** [comment]
> sure @wsvn53 [Build target adb-demo_2022-12-07T14-10-38.txt](https://github.com/wsvn53/adb-mobile/files/10176309/Build.target.adb-demo_2022-12-07T14-10-38.txt)

Oh sorry, I mean you can send me the build logs of compiling libadb by `make` command, not the xcode project build logs.

**Comment by cagnulein** [comment]
@wsvn53 sorry for the delay. Here you are
[log.rtf.zip](https://github.com/wsvn53/adb-mobile/files/10205744/log.rtf.zip)

**Comment by wsvn53** [comment]
> @wsvn53 sorry for the delay. Here you are [log.rtf.zip](https://github.com/wsvn53/adb-mobile/files/10205744/log.rtf.zip)

```
CMake Error at vendor/boringssl/CMakeLists.txt:51 (message):
  Could not find Go
```

I think the issue was caused by no golang installed, please `brew install go` to install the newest version of golang.

**Comment by cagnulein** [comment]
fixed! @wsvn53 sorry for the dumb mistake!
