### ISSUE TITLE
Please. Update for Xcode 14. 

### ISSUE THREAD

**Issue by mirroringcontact** [wsvn53/adb-mobile#2]
Thank you. If you want I can pay

**Comment by cagnulein** [comment]
@mirroringcontact i'm going to do the same, I will let you know

**Comment by wsvn53** [comment]
This is caused by mismatched protobuf version, please update the latest code of adb-mobile and execute:

```
brew unlink protobuf && brew install porting/protobuf.rb
```

This command will install correct version of protobuf, after that, you can execute `make` again to re-compile libadb.
