### ISSUE TITLE
Setting ADB Public & Private Key Files

### ISSUE THREAD

**Issue by kishanios123** [wsvn53/adb-mobile#5]
I'm looking to set up my ADB Public & Private key files independently. How can I initially pass these files?

**Comment by wsvn53** [comment]
You can simply change the HOME path of adb to load your adb public&private pair. You can infer this line code https://github.com/wsvn53/adb-mobile/blob/1513bcf058fc09eb34e00b5c91da5115e5c4b36b/porting/adb/include/adb_public.h#L43
